"""empty message

Revision ID: 18108ebce7bd
Revises: 25de20b53e7a
Create Date: 2020-06-01 16:20:27.736249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18108ebce7bd'
down_revision = '25de20b53e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('diet', sa.String(length=140), nullable=True))
    op.add_column('recipes', sa.Column('spiceLevel', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('diet', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'diet')
    op.drop_column('recipes', 'spiceLevel')
    op.drop_column('recipes', 'diet')
    # ### end Alembic commands ###
