"""empty message

Revision ID: 25de20b53e7a
Revises: 708bd4446a24
Create Date: 2020-05-27 17:45:41.878587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25de20b53e7a'
down_revision = '708bd4446a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ingredients_knownIngredients'), 'ingredients', ['knownIngredients'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredients_knownIngredients'), table_name='ingredients')
    # ### end Alembic commands ###
