"""empty message

Revision ID: f72625ad52bc
Revises: 18108ebce7bd
Create Date: 2020-06-03 01:22:10.974879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72625ad52bc'
down_revision = '18108ebce7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('popularity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'popularity')
    # ### end Alembic commands ###
