"""empty message

Revision ID: 3d5f7f60f04e
Revises: f88a95783bcb
Create Date: 2020-05-24 19:02:14.192584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5f7f60f04e'
down_revision = 'f88a95783bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipeingredients', sa.Column('units', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipeingredients', 'units')
    # ### end Alembic commands ###
