"""users table

Revision ID: 62d5edcfa746
Revises: c7ecff358a42
Create Date: 2020-05-09 17:31:20.695999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d5edcfa746'
down_revision = 'c7ecff358a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient', sa.String(length=140), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fridge_ingredient'), 'fridge', ['ingredient'], unique=False)
    op.create_index(op.f('ix_fridge_quantity'), 'fridge', ['quantity'], unique=False)
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('registered_on', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registered_on')
    op.drop_column('user', 'confirmed_on')
    op.drop_column('user', 'confirmed')
    op.drop_column('user', 'admin')
    op.drop_index(op.f('ix_fridge_quantity'), table_name='fridge')
    op.drop_index(op.f('ix_fridge_ingredient'), table_name='fridge')
    op.drop_table('fridge')
    # ### end Alembic commands ###
