"""empty message

Revision ID: 708bd4446a24
Revises: 8aa42d633da2
Create Date: 2020-05-26 17:48:06.054246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708bd4446a24'
down_revision = '8aa42d633da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knownIngredients', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('fridges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fridges_quantity'), 'fridges', ['quantity'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linktwo',
    sa.Column('fridges_id', sa.Integer(), nullable=False),
    sa.Column('ingredients_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fridges_id'], ['fridges.id'], ),
    sa.ForeignKeyConstraint(['ingredients_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('fridges_id', 'ingredients_id')
    )
    op.create_table('recipeingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('units', sa.String(length=140), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link',
    sa.Column('recipeingredients_id', sa.Integer(), nullable=False),
    sa.Column('ingredients_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredients_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipeingredients_id'], ['recipeingredients.id'], ),
    sa.PrimaryKeyConstraint('recipeingredients_id', 'ingredients_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    op.drop_table('recipeingredients')
    op.drop_table('linktwo')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_fridges_quantity'), table_name='fridges')
    op.drop_table('fridges')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
