"""empty message

Revision ID: 8aa42d633da2
Revises: 3d5f7f60f04e
Create Date: 2020-05-24 20:14:18.484635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa42d633da2'
down_revision = '3d5f7f60f04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('title', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'title')
    # ### end Alembic commands ###
