"""users table

Revision ID: 2142aa242f80
Revises: 1268c05a3a53
Create Date: 2020-05-09 17:42:32.470479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2142aa242f80'
down_revision = '1268c05a3a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient', sa.String(length=140), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fridge_ingredient'), 'fridge', ['ingredient'], unique=False)
    op.create_index(op.f('ix_fridge_quantity'), 'fridge', ['quantity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fridge_quantity'), table_name='fridge')
    op.drop_index(op.f('ix_fridge_ingredient'), table_name='fridge')
    op.drop_table('fridge')
    # ### end Alembic commands ###
